name: plan

on:
  pull_request:
    branches:
      - main

env:
  target: ubuntu-latest

jobs:
  tflint:
    strategy:
      matrix:
        os: [env.target]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.4.0
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache Plugins
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.46.1

      - name: Initialise
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Lint
        run: tflint -f compact

  terraform-cloud-speculative-run:
    strategy:
      matrix:
        os: [env.target]

    needs: [tflint]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      pull-requests: write
      issues: write

    env:
      TF_CLOUD_ORGANIZATION: "grendel-consulting"
      TF_WORKSPACE: "codebases"
      TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
      CONFIG_DIRECTORY: "./"

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.4.0
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure Terraform Cloud
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}
          speculative: true

      - name: Trigger a Terraform Cloud Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
          plan_only: true

      - name: Fetch the Plan Output
        uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.0
        id: plan-output
        with:
          plan: ${{ steps.run.outputs.plan_id }}

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Terraform Cloud Plan Output')
            })
            const output = `#### Terraform Cloud Plan Output
               Plan: ${{ steps.plan-output.outputs.add }} to add, ${{ steps.plan-output.outputs.change }} to change, ${{ steps.plan-output.outputs.destroy }} to destroy.
               [Terraform Cloud Plan](${{ steps.run.outputs.run_link }})
               `
            // 3. If we have a comment, update it, otherwise create a new one
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }
